name: Run All Actions

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  run-action1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout saucedemo
        uses: actions/checkout@v3

      - name: Run Action 1
        uses: ./saucedemo/.github/workflows/action.yml

  run-action2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout belajarcypress
        uses: actions/checkout@v3

      - name: Run Action 2
        uses: ./belajarcypress/.github/workflows/action.yml