name: Run All Actions

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  run-action1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout saucedemo
        uses: actions/checkout@v3

      - name: Run saucedemo
        run: |
          cd saucedemo/.github/workflows && npx act action.yml
          # Jalankan action1.yml sesuai dengan cara yang diperlukan
          #npx act action.yml  # Sesuaikan dengan cara Anda mengeksekusi action

  run-action2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout belajarcypress
        uses: actions/checkout@v3

      - name: Run belajarcypress
        run: |
          cd belajarcypress/.github/workflows
          # Jalankan action2.yml sesuai dengan cara yang diperlukan
          npx act action.yml  
          # Sesuaikan dengan cara Anda mengeksekusi action