name: Run All Actions

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  run-action-saucedemo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout saucedemo
        uses: actions/checkout@v3

      - name: Run saucedemo
        run: |
          cd saucedemo/.github/workflows
          # Menjalankan action1.yml jika ada perintah yang sesuai
          npm install
            
      - name: Run cypress saucedemo
        run: |
          cd saucedemo/
          npx cypress run 

  run-action-belajarcypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout belajarcypress
        uses: actions/checkout@v3

      - name: Run belajarcypress
        run: |
          cd belajarcypress/.github/workflows
          # Menjalankan action1.yml jika ada perintah yang sesuai
          npm install
            
      - name: Run cypress belajarcypress
        run: |
          cd belajarcypress/
          npx cypress run 
